name: Add a git tag for the release

on:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  main:
    name: tag the commit
    runs-on: ubuntu-latest
    if: "${{ startsWith(github.event.head_commit.message, 'REL: ') }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # with:
        #   repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract version from commit message
        id: extract_version
        run: |
          VERSION=$(echo "${{ github.event.head_commit.message }}" | grep -oP '(?<=REL: )\d+\.\d+\.\d+')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Extract tag message from commit message
        id: extract_message
        run: |
          MESSAGE=$(echo "${{ github.event.head_commit.message }}" | sed "s/${{ steps.extract_version.outputs.version }}//" )
          echo "message=$MESSAGE" >> $GITHUB_OUTPUT
      - name: Create Git Tag
        run: |
          VERSION="${{ steps.extract_version.outputs.version }}"
          MESSAGE="${{ steps.extract_message.outputs.message }}"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag "$VERSION" -m "$MESSAGE"
          git push origin $VERSION
